// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"week04/internal/biz"
	"week04/internal/data"
	"week04/internal/pkg/database"
	"week04/internal/service"

	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHelloServer(dsnURI string) *service.HelloServer {
	db := database.InitDB(dsnURI)
	messageRepo := data.NewMessageRepo(db)
	messageBiz := biz.NewMessageBiz(messageRepo)
	helloServer := service.NewHelloServer(messageBiz)
	return helloServer
}

// wire.go:

var dataRepoSet = wire.NewSet(data.NewMessageRepo, wire.Bind(new(biz.MessageRepo), new(*data.MessageRepo)))
